add kind ingress
camunda-community-hub/camunda8-greenfield-installation pull request #4
Opened 2022-08-18 21:19 UTC by plungu

2022-08-22 13:35 UTC, falko requested changes
Looks good so far. I'd only suggest to make the ingress completely optional. Did you test running the values without ingress?

2022-08-22 13:35 UTC, falko commented on kind/config.yaml
> +    protocol: TCP
Shouldn't this be optional, e.g. in a second example file that is only used when using the `camunda-ingress` target?

2022-08-22 13:41 UTC, falko commented
Depends on https://github.com/camunda-community-hub/camunda-8-helm-profiles/pull/12

2022-08-31 16:38 UTC, falko commented on README.md
> +`make camunda-ingress chartValues=../../camunda-8-helm-profiles/development/camunda-values.yaml,../../camunda-8-helm-profiles/ingress-kind/camunda-values.yaml`
This would be nice in the Helm profiles readme to show people how to invoke custom targets and combine values files

2022-10-21 06:32 UTC, falko commented
@plungu we should get this done before #3 happens

2022-11-05 14:55 UTC, plungu commented on kind/config.yaml
> +    protocol: TCP
This doesn't seem to effect the startup of the development/default profile.

2022-11-09 00:36 UTC, upgradingdave commented
Merged this into camunda-8-helm-profiles

2022-11-09 00:36 UTC, closed without merging